[package]
name = "SOCreateYourOwnGit"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
clap = { version = "4.5.37", features = ["derive"] }
flate2 = "1.0.34"
thiserror = "1.0.38"
sha1 = "0.10"   
hex = "0.4"
